### ISSUE TITLE
[Feature] Image Reordering

### ISSUE THREAD

**Issue by avayedawadi** [GTBitsOfGood/southface#169]
### Description

- In a digital library card, images can be added and deleted once the card is created. However, the order of the cards cannot currently be changed.
- We need a way to drag and drop images around and allow for the images to be reordered. Drag and drop is the preferred method but please contact the EM if you have another way to effectively reorder the images.
![image](https://github.com/GTBitsOfGood/southface/assets/45608655/afeab32b-24d0-44af-992a-7ad99ecded57)

### Acceptance Criteria

- [ ] Images can be reordered easily within an already created digital library card.
- [ ] The reordering also changes the ordering in the backend (the reordering must be persistent, it should not just happen in the frontend).
- [ ] The reordering uses a drag and drop method.
- [ ] Images can only be reordered in "edit" mode.
- [ ] The first image in the ordering should become the thumbnail for this card (this should happen automatically but if it doesn't then this will need to be implemented).

### Other Notes

- To get to a digital library card, first log in as an admin (message EM for details if needed). Then click a building type and a category. Click on any given card. There is a small edit button in the top right, click this and this allows you to see edit mode.

**Comment by mujtabach2** [comment]
Instead of a drag-and-drop interface, you could allow users to assign a numerical order to each image. Or you can make a dropdown menu next to/on each image where users can select their desired position in the sequence.

if you want to use drag and drop each image can be wrapped in a draggable element and implement js to track the event and a function that handles the actual reordering
